robot_mover_node:
  ros__parameters:
    node_rate: 4.0
    velocity_topic: "commands/velocity"
    linear_vel: 0.3
    angular_vel: 0.5
    turning_time: 2.0                       # Seconds
    max_loss_time: 1.0                      # Seconds. [1.0 - inf]

collision_detector_node:
  ros__parameters:
    node_rate: 5.0
    collision_distance: 0.3
    laser_topic: "scan"
    left_range_y: [0.10, 0.20]
    right_range_y: [-0.10, -0.20]
    front_range_y: [-0.10, 0.10]
    fixed_frame: "laser"
    child_frame: "collision_laser"
    transform_coords: [0.0, 0.0, 0.0, 0.0, 3.14, 0.0]